### ISSUE TITLE
A question about depth test..

### ISSUE THREAD

**Issue by fuxihao66** [jaredtao/QtOpenGL#1]
Sorry, I'm just a novice about OpenGL. I've found some problem in the "hello triangles". Although you've enable depth test, it seems that the depth writing has been disabled and they are shown in the order of rendering.

**Comment by jaredtao** [comment]
you can see this article
https://learnopengl.com/Advanced-OpenGL/Depth-testing

**Comment by fuxihao66** [comment]
I‘am still confused... Anyway, thanks a lot. I'll try by myself.
